/*
  This class is responsible for generating items while new users are onboarding.
  Auto generates items with retrieving the number of:
    * Adults
    * Children
    * Baby
    * Elderly
    * Pets
  
  The values that are generated by this class can be edited under the /constants.

*/

import {
  DRINK_BASES,
  FOOD_BASES,
  ELECTRONIC_BASES,
  CLOTHING_BASES,
  MEDICAL_BASES,
  DOCUMENT_BASES,
  SPECIAL_CARE_BASES,
  HYGIENE_BASES,
} from './constants';
import { ItemForUI, ItemsForUI } from './interfaces';
import { GeneratorNumberTypes } from './types';

export function itemGenerator({
  adult,
  children,
  elderly,
  baby,
  pet,
}: GeneratorNumberTypes): ItemsForUI {
  try {
    const result: ItemsForUI = {
      foods: generateFoods({ adult, children, elderly, baby, pet }),
      drinks: generateDrinks({ adult, children, elderly, baby, pet }),
      electronics: generateElectronics({ adult, children, elderly, baby, pet }),
      clothings: generateClothings({ adult, children, elderly, baby, pet }),
      medicals: generateMedicals({ adult, children, elderly, baby, pet }),
      documents: generateDocuments({ adult, children, elderly, baby, pet }),
      specialCares: generateSpecialCares({ adult, children, elderly, baby, pet }),
      hygienes: generateHygienes({ adult, children, elderly, baby, pet }),
    };

    return result;
  } catch (error) {
    throw new Error(`Error generating items: ${error}`);
  }
}

function generateFoods({ adult, children, elderly, baby, pet }: GeneratorNumberTypes): ItemForUI[] {
  try {
    const today = new Date();
    const sixMonthsLater = new Date(today);
    sixMonthsLater.setMonth(today.getMonth() + 6);
    const expiryDate = sixMonthsLater.toISOString();

    const items: ItemForUI[] = [];

    if (adult > 0) {
      items.push({
        header: FOOD_BASES.adult.header,
        quantity: adult * FOOD_BASES.adult.quantity,
        expiry_date: expiryDate,
      });
    }

    if (children > 0) {
      items.push({
        header: FOOD_BASES.children.header,
        quantity: children * FOOD_BASES.children.quantity,
        expiry_date: expiryDate,
      });
    }

    if (elderly > 0) {
      items.push({
        header: FOOD_BASES.elderly.header,
        quantity: elderly * FOOD_BASES.elderly.quantity,
        expiry_date: expiryDate,
      });
    }

    if (baby > 0) {
      items.push({
        header: FOOD_BASES.baby.header,
        quantity: baby * FOOD_BASES.baby.quantity,
        expiry_date: expiryDate,
      });
    }

    if (pet > 0) {
      items.push({
        header: FOOD_BASES.pet.header,
        quantity: pet * FOOD_BASES.pet.quantity,
        expiry_date: expiryDate,
      });
    }

    return items;
  } catch (error) {
    throw new Error(`Error generating foods: ${error}`);
  }
}

function generateDrinks({
  adult,
  children,
  elderly,
  baby,
  pet,
}: GeneratorNumberTypes): ItemForUI[] {
  try {
    const items: ItemForUI[] = [];

    if (adult > 0) {
      items.push({
        header: DRINK_BASES.adult.header,
        quantity: 0,
        liters: adult * DRINK_BASES.adult.liters,
      });
    }

    if (children > 0) {
      items.push({
        header: DRINK_BASES.children.header,
        quantity: 0,
        liters: children * DRINK_BASES.children.liters,
      });
    }

    if (elderly > 0) {
      items.push({
        header: DRINK_BASES.elderly.header,
        quantity: 0,
        liters: elderly * DRINK_BASES.elderly.liters,
      });
    }

    if (baby > 0) {
      items.push({
        header: DRINK_BASES.baby.header,
        quantity: 0,
        liters: baby * DRINK_BASES.baby.liters,
      });
    }

    if (pet > 0) {
      items.push({
        header: DRINK_BASES.pet.header,
        quantity: 0,
        liters: pet * DRINK_BASES.pet.liters,
      });
    }

    return items;
  } catch (error) {
    throw new Error(`Error generating drinks: ${error}`);
  }
}

function generateElectronics({
  adult,
  children,
  elderly,
  baby,
  pet,
}: GeneratorNumberTypes): ItemForUI[] {
  try {
    const items: ItemForUI[] = [];

    if (adult > 0) {
      items.push({
        header: ELECTRONIC_BASES.adult.header,
        quantity: adult * ELECTRONIC_BASES.adult.quantity,
        charge: ELECTRONIC_BASES.adult.charge,
      });
    }

    if (children > 0) {
      items.push({
        header: ELECTRONIC_BASES.children.header,
        quantity: children * ELECTRONIC_BASES.children.quantity,
        charge: ELECTRONIC_BASES.children.charge,
      });
    }

    if (elderly > 0) {
      items.push({
        header: ELECTRONIC_BASES.elderly.header,
        quantity: elderly * ELECTRONIC_BASES.elderly.quantity,
        charge: ELECTRONIC_BASES.elderly.charge,
      });
    }

    if (baby > 0) {
      items.push({
        header: ELECTRONIC_BASES.baby.header,
        quantity: baby * ELECTRONIC_BASES.baby.quantity,
        charge: ELECTRONIC_BASES.baby.charge,
      });
    }

    if (pet > 0) {
      items.push({
        header: ELECTRONIC_BASES.pet.header,
        quantity: pet * ELECTRONIC_BASES.pet.quantity,
        charge: ELECTRONIC_BASES.pet.charge,
      });
    }

    return items;
  } catch (error) {
    throw new Error(`Error generating electronics: ${error}`);
  }
}

function generateClothings({
  adult,
  children,
  elderly,
  baby,
  pet,
}: GeneratorNumberTypes): ItemForUI[] {
  try {
    const items: ItemForUI[] = [];

    if (adult > 0) {
      items.push({
        header: CLOTHING_BASES.adult.header,
        quantity: adult * CLOTHING_BASES.adult.quantity,
        season: CLOTHING_BASES.adult.season,
      });
    }

    if (children > 0) {
      items.push({
        header: CLOTHING_BASES.children.header,
        quantity: children * CLOTHING_BASES.children.quantity,
        season: CLOTHING_BASES.children.season,
      });
    }

    if (elderly > 0) {
      items.push({
        header: CLOTHING_BASES.elderly.header,
        quantity: elderly * CLOTHING_BASES.elderly.quantity,
        season: CLOTHING_BASES.elderly.season,
      });
    }

    if (baby > 0) {
      items.push({
        header: CLOTHING_BASES.baby.header,
        quantity: baby * CLOTHING_BASES.baby.quantity,
        season: CLOTHING_BASES.baby.season,
      });
    }

    if (pet > 0) {
      items.push({
        header: CLOTHING_BASES.pet.header,
        quantity: pet * CLOTHING_BASES.pet.quantity,
        season: CLOTHING_BASES.pet.season,
      });
    }

    return items;
  } catch (error) {
    throw new Error(`Error generating clothings: ${error}`);
  }
}

function generateMedicals({
  adult,
  children,
  elderly,
  baby,
  pet,
}: GeneratorNumberTypes): ItemForUI[] {
  try {
    const items: ItemForUI[] = [];

    if (adult > 0) {
      items.push({
        header: MEDICAL_BASES.adult.header,
        quantity: adult * MEDICAL_BASES.adult.quantity,
        medicine_type: MEDICAL_BASES.adult.medicine_type,
      });
    }

    if (children > 0) {
      items.push({
        header: MEDICAL_BASES.children.header,
        quantity: children * MEDICAL_BASES.children.quantity,
        medicine_type: MEDICAL_BASES.children.medicine_type,
      });
    }

    if (elderly > 0) {
      items.push({
        header: MEDICAL_BASES.elderly.header,
        quantity: elderly * MEDICAL_BASES.elderly.quantity,
        medicine_type: MEDICAL_BASES.elderly.medicine_type,
      });
    }

    if (baby > 0) {
      items.push({
        header: MEDICAL_BASES.baby.header,
        quantity: baby * MEDICAL_BASES.baby.quantity,
        medicine_type: MEDICAL_BASES.baby.medicine_type,
      });
    }

    if (pet > 0) {
      items.push({
        header: MEDICAL_BASES.pet.header,
        quantity: pet * MEDICAL_BASES.pet.quantity,
        medicine_type: MEDICAL_BASES.pet.medicine_type,
      });
    }

    return items;
  } catch (error) {
    throw new Error(`Error generating medicals: ${error}`);
  }
}

function generateDocuments({
  adult,
  children,
  elderly,
  baby,
  pet,
}: GeneratorNumberTypes): ItemForUI[] {
  try {
    const items: ItemForUI[] = [];

    if (adult > 0) {
      items.push({
        header: DOCUMENT_BASES.adult.header,
        quantity: adult * DOCUMENT_BASES.adult.quantity,
        document_type: DOCUMENT_BASES.adult.document_type,
      });
    }

    if (children > 0) {
      items.push({
        header: DOCUMENT_BASES.children.header,
        quantity: children * DOCUMENT_BASES.children.quantity,
        document_type: DOCUMENT_BASES.children.document_type,
      });
    }

    if (elderly > 0) {
      items.push({
        header: DOCUMENT_BASES.elderly.header,
        quantity: elderly * DOCUMENT_BASES.elderly.quantity,
        document_type: DOCUMENT_BASES.elderly.document_type,
      });
    }

    if (baby > 0) {
      items.push({
        header: DOCUMENT_BASES.baby.header,
        quantity: baby * DOCUMENT_BASES.baby.quantity,
        document_type: DOCUMENT_BASES.baby.document_type,
      });
    }

    if (pet > 0) {
      items.push({
        header: DOCUMENT_BASES.pet.header,
        quantity: pet * DOCUMENT_BASES.pet.quantity,
        document_type: DOCUMENT_BASES.pet.document_type,
      });
    }

    return items;
  } catch (error) {
    throw new Error(`Error generating documents: ${error}`);
  }
}

function generateSpecialCares({
  adult,
  children,
  elderly,
  baby,
  pet,
}: GeneratorNumberTypes): ItemForUI[] {
  try {
    const items: ItemForUI[] = [];

    if (adult > 0) {
      items.push({
        header: SPECIAL_CARE_BASES.adult.header,
        quantity: adult * SPECIAL_CARE_BASES.adult.quantity,
        belongs_to: SPECIAL_CARE_BASES.adult.belongs_to,
      });
    }

    if (children > 0) {
      items.push({
        header: SPECIAL_CARE_BASES.children.header,
        quantity: children * SPECIAL_CARE_BASES.children.quantity,
        belongs_to: SPECIAL_CARE_BASES.children.belongs_to,
      });
    }

    if (elderly > 0) {
      items.push({
        header: SPECIAL_CARE_BASES.elderly.header,
        quantity: elderly * SPECIAL_CARE_BASES.elderly.quantity,
        belongs_to: SPECIAL_CARE_BASES.elderly.belongs_to,
      });
    }

    if (baby > 0) {
      items.push({
        header: SPECIAL_CARE_BASES.baby.header,
        quantity: baby * SPECIAL_CARE_BASES.baby.quantity,
        belongs_to: SPECIAL_CARE_BASES.baby.belongs_to,
      });
    }

    if (pet > 0) {
      items.push({
        header: SPECIAL_CARE_BASES.pet.header,
        quantity: pet * SPECIAL_CARE_BASES.pet.quantity,
        belongs_to: SPECIAL_CARE_BASES.pet.belongs_to,
      });
    }

    return items;
  } catch (error) {
    throw new Error(`Error generating specialCares: ${error}`);
  }
}

function generateHygienes({
  adult,
  children,
  elderly,
  baby,
  pet,
}: GeneratorNumberTypes): ItemForUI[] {
  try {
    const items: ItemForUI[] = [];

    if (adult > 0) {
      items.push({
        header: HYGIENE_BASES.adult.header,
        quantity: adult * HYGIENE_BASES.adult.quantity,
        belongs_to: HYGIENE_BASES.adult.belongs_to,
      });
    }

    if (children > 0) {
      items.push({
        header: HYGIENE_BASES.children.header,
        quantity: children * HYGIENE_BASES.children.quantity,
        belongs_to: HYGIENE_BASES.children.belongs_to,
      });
    }

    if (elderly > 0) {
      items.push({
        header: HYGIENE_BASES.elderly.header,
        quantity: elderly * HYGIENE_BASES.elderly.quantity,
        belongs_to: HYGIENE_BASES.elderly.belongs_to,
      });
    }

    if (baby > 0) {
      items.push({
        header: HYGIENE_BASES.baby.header,
        quantity: baby * HYGIENE_BASES.baby.quantity,
        belongs_to: HYGIENE_BASES.baby.belongs_to,
      });
    }

    if (pet > 0) {
      items.push({
        header: HYGIENE_BASES.pet.header,
        quantity: pet * HYGIENE_BASES.pet.quantity,
        belongs_to: HYGIENE_BASES.pet.belongs_to,
      });
    }

    return items;
  } catch (error) {
    throw new Error(`Error generating hygienes: ${error}`);
  }
}
